### ISSUE TITLE
Steam Version

### ISSUE THREAD

**Issue by Futuza** [krisives/divinityfourplayer#1]
Hi there @krisives, on the readme you mentioned you wanted the Steam version tested.  It works fine, but will correct/patch itself back if you tell steam to verify the file integrity or if an update is sent out by Steam.

eg, don't click verify integrity of game files if you don't want Steam to remove the patch:
![image](https://user-images.githubusercontent.com/4450419/27816586-b24d0c48-6049-11e7-8104-48befd629801.png)

**Comment by krisives** [comment]
Thanks!

**Comment by krisives** [comment]
c9088178f2ed172117621af3ba13cd9ad2910432
